# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rummens/Documents/School/HvA/Project_SE/jiskefet-api-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rummens/Documents/School/HvA/Project_SE/jiskefet-api-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rummens/Documents/School/HvA/Project_SE/jiskefet-api-cpp/CMakeFiles /home/rummens/Documents/School/HvA/Project_SE/jiskefet-api-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rummens/Documents/School/HvA/Project_SE/jiskefet-api-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jiskefet-api-cpp-example

# Build rule for target.
jiskefet-api-cpp-example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jiskefet-api-cpp-example
.PHONY : jiskefet-api-cpp-example

# fast build rule for target.
jiskefet-api-cpp-example/fast:
	$(MAKE) -f CMakeFiles/jiskefet-api-cpp-example.dir/build.make CMakeFiles/jiskefet-api-cpp-example.dir/build
.PHONY : jiskefet-api-cpp-example/fast

#=============================================================================
# Target rules for targets named JiskefetApiCpp

# Build rule for target.
JiskefetApiCpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JiskefetApiCpp
.PHONY : JiskefetApiCpp

# fast build rule for target.
JiskefetApiCpp/fast:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/build
.PHONY : JiskefetApiCpp/fast

src/Example.o: src/Example.cpp.o

.PHONY : src/Example.o

# target to build an object file
src/Example.cpp.o:
	$(MAKE) -f CMakeFiles/jiskefet-api-cpp-example.dir/build.make CMakeFiles/jiskefet-api-cpp-example.dir/src/Example.cpp.o
.PHONY : src/Example.cpp.o

src/Example.i: src/Example.cpp.i

.PHONY : src/Example.i

# target to preprocess a source file
src/Example.cpp.i:
	$(MAKE) -f CMakeFiles/jiskefet-api-cpp-example.dir/build.make CMakeFiles/jiskefet-api-cpp-example.dir/src/Example.cpp.i
.PHONY : src/Example.cpp.i

src/Example.s: src/Example.cpp.s

.PHONY : src/Example.s

# target to generate assembly for a file
src/Example.cpp.s:
	$(MAKE) -f CMakeFiles/jiskefet-api-cpp-example.dir/build.make CMakeFiles/jiskefet-api-cpp-example.dir/src/Example.cpp.s
.PHONY : src/Example.cpp.s

src/JiskefetApi.o: src/JiskefetApi.cpp.o

.PHONY : src/JiskefetApi.o

# target to build an object file
src/JiskefetApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/JiskefetApi.cpp.o
.PHONY : src/JiskefetApi.cpp.o

src/JiskefetApi.i: src/JiskefetApi.cpp.i

.PHONY : src/JiskefetApi.i

# target to preprocess a source file
src/JiskefetApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/JiskefetApi.cpp.i
.PHONY : src/JiskefetApi.cpp.i

src/JiskefetApi.s: src/JiskefetApi.cpp.s

.PHONY : src/JiskefetApi.s

# target to generate assembly for a file
src/JiskefetApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/JiskefetApi.cpp.s
.PHONY : src/JiskefetApi.cpp.s

src/JiskefetFactory.o: src/JiskefetFactory.cpp.o

.PHONY : src/JiskefetFactory.o

# target to build an object file
src/JiskefetFactory.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/JiskefetFactory.cpp.o
.PHONY : src/JiskefetFactory.cpp.o

src/JiskefetFactory.i: src/JiskefetFactory.cpp.i

.PHONY : src/JiskefetFactory.i

# target to preprocess a source file
src/JiskefetFactory.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/JiskefetFactory.cpp.i
.PHONY : src/JiskefetFactory.cpp.i

src/JiskefetFactory.s: src/JiskefetFactory.cpp.s

.PHONY : src/JiskefetFactory.s

# target to generate assembly for a file
src/JiskefetFactory.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/JiskefetFactory.cpp.s
.PHONY : src/JiskefetFactory.cpp.s

src/cpprest-client/ApiClient.o: src/cpprest-client/ApiClient.cpp.o

.PHONY : src/cpprest-client/ApiClient.o

# target to build an object file
src/cpprest-client/ApiClient.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiClient.cpp.o
.PHONY : src/cpprest-client/ApiClient.cpp.o

src/cpprest-client/ApiClient.i: src/cpprest-client/ApiClient.cpp.i

.PHONY : src/cpprest-client/ApiClient.i

# target to preprocess a source file
src/cpprest-client/ApiClient.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiClient.cpp.i
.PHONY : src/cpprest-client/ApiClient.cpp.i

src/cpprest-client/ApiClient.s: src/cpprest-client/ApiClient.cpp.s

.PHONY : src/cpprest-client/ApiClient.s

# target to generate assembly for a file
src/cpprest-client/ApiClient.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiClient.cpp.s
.PHONY : src/cpprest-client/ApiClient.cpp.s

src/cpprest-client/ApiConfiguration.o: src/cpprest-client/ApiConfiguration.cpp.o

.PHONY : src/cpprest-client/ApiConfiguration.o

# target to build an object file
src/cpprest-client/ApiConfiguration.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiConfiguration.cpp.o
.PHONY : src/cpprest-client/ApiConfiguration.cpp.o

src/cpprest-client/ApiConfiguration.i: src/cpprest-client/ApiConfiguration.cpp.i

.PHONY : src/cpprest-client/ApiConfiguration.i

# target to preprocess a source file
src/cpprest-client/ApiConfiguration.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiConfiguration.cpp.i
.PHONY : src/cpprest-client/ApiConfiguration.cpp.i

src/cpprest-client/ApiConfiguration.s: src/cpprest-client/ApiConfiguration.cpp.s

.PHONY : src/cpprest-client/ApiConfiguration.s

# target to generate assembly for a file
src/cpprest-client/ApiConfiguration.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiConfiguration.cpp.s
.PHONY : src/cpprest-client/ApiConfiguration.cpp.s

src/cpprest-client/ApiException.o: src/cpprest-client/ApiException.cpp.o

.PHONY : src/cpprest-client/ApiException.o

# target to build an object file
src/cpprest-client/ApiException.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiException.cpp.o
.PHONY : src/cpprest-client/ApiException.cpp.o

src/cpprest-client/ApiException.i: src/cpprest-client/ApiException.cpp.i

.PHONY : src/cpprest-client/ApiException.i

# target to preprocess a source file
src/cpprest-client/ApiException.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiException.cpp.i
.PHONY : src/cpprest-client/ApiException.cpp.i

src/cpprest-client/ApiException.s: src/cpprest-client/ApiException.cpp.s

.PHONY : src/cpprest-client/ApiException.s

# target to generate assembly for a file
src/cpprest-client/ApiException.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ApiException.cpp.s
.PHONY : src/cpprest-client/ApiException.cpp.s

src/cpprest-client/HttpContent.o: src/cpprest-client/HttpContent.cpp.o

.PHONY : src/cpprest-client/HttpContent.o

# target to build an object file
src/cpprest-client/HttpContent.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/HttpContent.cpp.o
.PHONY : src/cpprest-client/HttpContent.cpp.o

src/cpprest-client/HttpContent.i: src/cpprest-client/HttpContent.cpp.i

.PHONY : src/cpprest-client/HttpContent.i

# target to preprocess a source file
src/cpprest-client/HttpContent.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/HttpContent.cpp.i
.PHONY : src/cpprest-client/HttpContent.cpp.i

src/cpprest-client/HttpContent.s: src/cpprest-client/HttpContent.cpp.s

.PHONY : src/cpprest-client/HttpContent.s

# target to generate assembly for a file
src/cpprest-client/HttpContent.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/HttpContent.cpp.s
.PHONY : src/cpprest-client/HttpContent.cpp.s

src/cpprest-client/JsonBody.o: src/cpprest-client/JsonBody.cpp.o

.PHONY : src/cpprest-client/JsonBody.o

# target to build an object file
src/cpprest-client/JsonBody.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/JsonBody.cpp.o
.PHONY : src/cpprest-client/JsonBody.cpp.o

src/cpprest-client/JsonBody.i: src/cpprest-client/JsonBody.cpp.i

.PHONY : src/cpprest-client/JsonBody.i

# target to preprocess a source file
src/cpprest-client/JsonBody.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/JsonBody.cpp.i
.PHONY : src/cpprest-client/JsonBody.cpp.i

src/cpprest-client/JsonBody.s: src/cpprest-client/JsonBody.cpp.s

.PHONY : src/cpprest-client/JsonBody.s

# target to generate assembly for a file
src/cpprest-client/JsonBody.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/JsonBody.cpp.s
.PHONY : src/cpprest-client/JsonBody.cpp.s

src/cpprest-client/ModelBase.o: src/cpprest-client/ModelBase.cpp.o

.PHONY : src/cpprest-client/ModelBase.o

# target to build an object file
src/cpprest-client/ModelBase.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ModelBase.cpp.o
.PHONY : src/cpprest-client/ModelBase.cpp.o

src/cpprest-client/ModelBase.i: src/cpprest-client/ModelBase.cpp.i

.PHONY : src/cpprest-client/ModelBase.i

# target to preprocess a source file
src/cpprest-client/ModelBase.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ModelBase.cpp.i
.PHONY : src/cpprest-client/ModelBase.cpp.i

src/cpprest-client/ModelBase.s: src/cpprest-client/ModelBase.cpp.s

.PHONY : src/cpprest-client/ModelBase.s

# target to generate assembly for a file
src/cpprest-client/ModelBase.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/ModelBase.cpp.s
.PHONY : src/cpprest-client/ModelBase.cpp.s

src/cpprest-client/MultipartFormData.o: src/cpprest-client/MultipartFormData.cpp.o

.PHONY : src/cpprest-client/MultipartFormData.o

# target to build an object file
src/cpprest-client/MultipartFormData.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/MultipartFormData.cpp.o
.PHONY : src/cpprest-client/MultipartFormData.cpp.o

src/cpprest-client/MultipartFormData.i: src/cpprest-client/MultipartFormData.cpp.i

.PHONY : src/cpprest-client/MultipartFormData.i

# target to preprocess a source file
src/cpprest-client/MultipartFormData.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/MultipartFormData.cpp.i
.PHONY : src/cpprest-client/MultipartFormData.cpp.i

src/cpprest-client/MultipartFormData.s: src/cpprest-client/MultipartFormData.cpp.s

.PHONY : src/cpprest-client/MultipartFormData.s

# target to generate assembly for a file
src/cpprest-client/MultipartFormData.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/MultipartFormData.cpp.s
.PHONY : src/cpprest-client/MultipartFormData.cpp.s

src/cpprest-client/Object.o: src/cpprest-client/Object.cpp.o

.PHONY : src/cpprest-client/Object.o

# target to build an object file
src/cpprest-client/Object.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/Object.cpp.o
.PHONY : src/cpprest-client/Object.cpp.o

src/cpprest-client/Object.i: src/cpprest-client/Object.cpp.i

.PHONY : src/cpprest-client/Object.i

# target to preprocess a source file
src/cpprest-client/Object.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/Object.cpp.i
.PHONY : src/cpprest-client/Object.cpp.i

src/cpprest-client/Object.s: src/cpprest-client/Object.cpp.s

.PHONY : src/cpprest-client/Object.s

# target to generate assembly for a file
src/cpprest-client/Object.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/Object.cpp.s
.PHONY : src/cpprest-client/Object.cpp.s

src/cpprest-client/api/AttachmentsApi.o: src/cpprest-client/api/AttachmentsApi.cpp.o

.PHONY : src/cpprest-client/api/AttachmentsApi.o

# target to build an object file
src/cpprest-client/api/AttachmentsApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/AttachmentsApi.cpp.o
.PHONY : src/cpprest-client/api/AttachmentsApi.cpp.o

src/cpprest-client/api/AttachmentsApi.i: src/cpprest-client/api/AttachmentsApi.cpp.i

.PHONY : src/cpprest-client/api/AttachmentsApi.i

# target to preprocess a source file
src/cpprest-client/api/AttachmentsApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/AttachmentsApi.cpp.i
.PHONY : src/cpprest-client/api/AttachmentsApi.cpp.i

src/cpprest-client/api/AttachmentsApi.s: src/cpprest-client/api/AttachmentsApi.cpp.s

.PHONY : src/cpprest-client/api/AttachmentsApi.s

# target to generate assembly for a file
src/cpprest-client/api/AttachmentsApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/AttachmentsApi.cpp.s
.PHONY : src/cpprest-client/api/AttachmentsApi.cpp.s

src/cpprest-client/api/AuthenticationApi.o: src/cpprest-client/api/AuthenticationApi.cpp.o

.PHONY : src/cpprest-client/api/AuthenticationApi.o

# target to build an object file
src/cpprest-client/api/AuthenticationApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/AuthenticationApi.cpp.o
.PHONY : src/cpprest-client/api/AuthenticationApi.cpp.o

src/cpprest-client/api/AuthenticationApi.i: src/cpprest-client/api/AuthenticationApi.cpp.i

.PHONY : src/cpprest-client/api/AuthenticationApi.i

# target to preprocess a source file
src/cpprest-client/api/AuthenticationApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/AuthenticationApi.cpp.i
.PHONY : src/cpprest-client/api/AuthenticationApi.cpp.i

src/cpprest-client/api/AuthenticationApi.s: src/cpprest-client/api/AuthenticationApi.cpp.s

.PHONY : src/cpprest-client/api/AuthenticationApi.s

# target to generate assembly for a file
src/cpprest-client/api/AuthenticationApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/AuthenticationApi.cpp.s
.PHONY : src/cpprest-client/api/AuthenticationApi.cpp.s

src/cpprest-client/api/FlpApi.o: src/cpprest-client/api/FlpApi.cpp.o

.PHONY : src/cpprest-client/api/FlpApi.o

# target to build an object file
src/cpprest-client/api/FlpApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/FlpApi.cpp.o
.PHONY : src/cpprest-client/api/FlpApi.cpp.o

src/cpprest-client/api/FlpApi.i: src/cpprest-client/api/FlpApi.cpp.i

.PHONY : src/cpprest-client/api/FlpApi.i

# target to preprocess a source file
src/cpprest-client/api/FlpApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/FlpApi.cpp.i
.PHONY : src/cpprest-client/api/FlpApi.cpp.i

src/cpprest-client/api/FlpApi.s: src/cpprest-client/api/FlpApi.cpp.s

.PHONY : src/cpprest-client/api/FlpApi.s

# target to generate assembly for a file
src/cpprest-client/api/FlpApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/FlpApi.cpp.s
.PHONY : src/cpprest-client/api/FlpApi.cpp.s

src/cpprest-client/api/LogsApi.o: src/cpprest-client/api/LogsApi.cpp.o

.PHONY : src/cpprest-client/api/LogsApi.o

# target to build an object file
src/cpprest-client/api/LogsApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/LogsApi.cpp.o
.PHONY : src/cpprest-client/api/LogsApi.cpp.o

src/cpprest-client/api/LogsApi.i: src/cpprest-client/api/LogsApi.cpp.i

.PHONY : src/cpprest-client/api/LogsApi.i

# target to preprocess a source file
src/cpprest-client/api/LogsApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/LogsApi.cpp.i
.PHONY : src/cpprest-client/api/LogsApi.cpp.i

src/cpprest-client/api/LogsApi.s: src/cpprest-client/api/LogsApi.cpp.s

.PHONY : src/cpprest-client/api/LogsApi.s

# target to generate assembly for a file
src/cpprest-client/api/LogsApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/LogsApi.cpp.s
.PHONY : src/cpprest-client/api/LogsApi.cpp.s

src/cpprest-client/api/OverviewApi.o: src/cpprest-client/api/OverviewApi.cpp.o

.PHONY : src/cpprest-client/api/OverviewApi.o

# target to build an object file
src/cpprest-client/api/OverviewApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/OverviewApi.cpp.o
.PHONY : src/cpprest-client/api/OverviewApi.cpp.o

src/cpprest-client/api/OverviewApi.i: src/cpprest-client/api/OverviewApi.cpp.i

.PHONY : src/cpprest-client/api/OverviewApi.i

# target to preprocess a source file
src/cpprest-client/api/OverviewApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/OverviewApi.cpp.i
.PHONY : src/cpprest-client/api/OverviewApi.cpp.i

src/cpprest-client/api/OverviewApi.s: src/cpprest-client/api/OverviewApi.cpp.s

.PHONY : src/cpprest-client/api/OverviewApi.s

# target to generate assembly for a file
src/cpprest-client/api/OverviewApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/OverviewApi.cpp.s
.PHONY : src/cpprest-client/api/OverviewApi.cpp.s

src/cpprest-client/api/RunsApi.o: src/cpprest-client/api/RunsApi.cpp.o

.PHONY : src/cpprest-client/api/RunsApi.o

# target to build an object file
src/cpprest-client/api/RunsApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/RunsApi.cpp.o
.PHONY : src/cpprest-client/api/RunsApi.cpp.o

src/cpprest-client/api/RunsApi.i: src/cpprest-client/api/RunsApi.cpp.i

.PHONY : src/cpprest-client/api/RunsApi.i

# target to preprocess a source file
src/cpprest-client/api/RunsApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/RunsApi.cpp.i
.PHONY : src/cpprest-client/api/RunsApi.cpp.i

src/cpprest-client/api/RunsApi.s: src/cpprest-client/api/RunsApi.cpp.s

.PHONY : src/cpprest-client/api/RunsApi.s

# target to generate assembly for a file
src/cpprest-client/api/RunsApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/RunsApi.cpp.s
.PHONY : src/cpprest-client/api/RunsApi.cpp.s

src/cpprest-client/api/SettingApi.o: src/cpprest-client/api/SettingApi.cpp.o

.PHONY : src/cpprest-client/api/SettingApi.o

# target to build an object file
src/cpprest-client/api/SettingApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/SettingApi.cpp.o
.PHONY : src/cpprest-client/api/SettingApi.cpp.o

src/cpprest-client/api/SettingApi.i: src/cpprest-client/api/SettingApi.cpp.i

.PHONY : src/cpprest-client/api/SettingApi.i

# target to preprocess a source file
src/cpprest-client/api/SettingApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/SettingApi.cpp.i
.PHONY : src/cpprest-client/api/SettingApi.cpp.i

src/cpprest-client/api/SettingApi.s: src/cpprest-client/api/SettingApi.cpp.s

.PHONY : src/cpprest-client/api/SettingApi.s

# target to generate assembly for a file
src/cpprest-client/api/SettingApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/SettingApi.cpp.s
.PHONY : src/cpprest-client/api/SettingApi.cpp.s

src/cpprest-client/api/SubsystemsApi.o: src/cpprest-client/api/SubsystemsApi.cpp.o

.PHONY : src/cpprest-client/api/SubsystemsApi.o

# target to build an object file
src/cpprest-client/api/SubsystemsApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/SubsystemsApi.cpp.o
.PHONY : src/cpprest-client/api/SubsystemsApi.cpp.o

src/cpprest-client/api/SubsystemsApi.i: src/cpprest-client/api/SubsystemsApi.cpp.i

.PHONY : src/cpprest-client/api/SubsystemsApi.i

# target to preprocess a source file
src/cpprest-client/api/SubsystemsApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/SubsystemsApi.cpp.i
.PHONY : src/cpprest-client/api/SubsystemsApi.cpp.i

src/cpprest-client/api/SubsystemsApi.s: src/cpprest-client/api/SubsystemsApi.cpp.s

.PHONY : src/cpprest-client/api/SubsystemsApi.s

# target to generate assembly for a file
src/cpprest-client/api/SubsystemsApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/SubsystemsApi.cpp.s
.PHONY : src/cpprest-client/api/SubsystemsApi.cpp.s

src/cpprest-client/api/UsersApi.o: src/cpprest-client/api/UsersApi.cpp.o

.PHONY : src/cpprest-client/api/UsersApi.o

# target to build an object file
src/cpprest-client/api/UsersApi.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/UsersApi.cpp.o
.PHONY : src/cpprest-client/api/UsersApi.cpp.o

src/cpprest-client/api/UsersApi.i: src/cpprest-client/api/UsersApi.cpp.i

.PHONY : src/cpprest-client/api/UsersApi.i

# target to preprocess a source file
src/cpprest-client/api/UsersApi.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/UsersApi.cpp.i
.PHONY : src/cpprest-client/api/UsersApi.cpp.i

src/cpprest-client/api/UsersApi.s: src/cpprest-client/api/UsersApi.cpp.s

.PHONY : src/cpprest-client/api/UsersApi.s

# target to generate assembly for a file
src/cpprest-client/api/UsersApi.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/api/UsersApi.cpp.s
.PHONY : src/cpprest-client/api/UsersApi.cpp.s

src/cpprest-client/model/CreateAttachmentDto.o: src/cpprest-client/model/CreateAttachmentDto.cpp.o

.PHONY : src/cpprest-client/model/CreateAttachmentDto.o

# target to build an object file
src/cpprest-client/model/CreateAttachmentDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateAttachmentDto.cpp.o
.PHONY : src/cpprest-client/model/CreateAttachmentDto.cpp.o

src/cpprest-client/model/CreateAttachmentDto.i: src/cpprest-client/model/CreateAttachmentDto.cpp.i

.PHONY : src/cpprest-client/model/CreateAttachmentDto.i

# target to preprocess a source file
src/cpprest-client/model/CreateAttachmentDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateAttachmentDto.cpp.i
.PHONY : src/cpprest-client/model/CreateAttachmentDto.cpp.i

src/cpprest-client/model/CreateAttachmentDto.s: src/cpprest-client/model/CreateAttachmentDto.cpp.s

.PHONY : src/cpprest-client/model/CreateAttachmentDto.s

# target to generate assembly for a file
src/cpprest-client/model/CreateAttachmentDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateAttachmentDto.cpp.s
.PHONY : src/cpprest-client/model/CreateAttachmentDto.cpp.s

src/cpprest-client/model/CreateFlpDto.o: src/cpprest-client/model/CreateFlpDto.cpp.o

.PHONY : src/cpprest-client/model/CreateFlpDto.o

# target to build an object file
src/cpprest-client/model/CreateFlpDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateFlpDto.cpp.o
.PHONY : src/cpprest-client/model/CreateFlpDto.cpp.o

src/cpprest-client/model/CreateFlpDto.i: src/cpprest-client/model/CreateFlpDto.cpp.i

.PHONY : src/cpprest-client/model/CreateFlpDto.i

# target to preprocess a source file
src/cpprest-client/model/CreateFlpDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateFlpDto.cpp.i
.PHONY : src/cpprest-client/model/CreateFlpDto.cpp.i

src/cpprest-client/model/CreateFlpDto.s: src/cpprest-client/model/CreateFlpDto.cpp.s

.PHONY : src/cpprest-client/model/CreateFlpDto.s

# target to generate assembly for a file
src/cpprest-client/model/CreateFlpDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateFlpDto.cpp.s
.PHONY : src/cpprest-client/model/CreateFlpDto.cpp.s

src/cpprest-client/model/CreateLogDto.o: src/cpprest-client/model/CreateLogDto.cpp.o

.PHONY : src/cpprest-client/model/CreateLogDto.o

# target to build an object file
src/cpprest-client/model/CreateLogDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateLogDto.cpp.o
.PHONY : src/cpprest-client/model/CreateLogDto.cpp.o

src/cpprest-client/model/CreateLogDto.i: src/cpprest-client/model/CreateLogDto.cpp.i

.PHONY : src/cpprest-client/model/CreateLogDto.i

# target to preprocess a source file
src/cpprest-client/model/CreateLogDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateLogDto.cpp.i
.PHONY : src/cpprest-client/model/CreateLogDto.cpp.i

src/cpprest-client/model/CreateLogDto.s: src/cpprest-client/model/CreateLogDto.cpp.s

.PHONY : src/cpprest-client/model/CreateLogDto.s

# target to generate assembly for a file
src/cpprest-client/model/CreateLogDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateLogDto.cpp.s
.PHONY : src/cpprest-client/model/CreateLogDto.cpp.s

src/cpprest-client/model/CreateRunDto.o: src/cpprest-client/model/CreateRunDto.cpp.o

.PHONY : src/cpprest-client/model/CreateRunDto.o

# target to build an object file
src/cpprest-client/model/CreateRunDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateRunDto.cpp.o
.PHONY : src/cpprest-client/model/CreateRunDto.cpp.o

src/cpprest-client/model/CreateRunDto.i: src/cpprest-client/model/CreateRunDto.cpp.i

.PHONY : src/cpprest-client/model/CreateRunDto.i

# target to preprocess a source file
src/cpprest-client/model/CreateRunDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateRunDto.cpp.i
.PHONY : src/cpprest-client/model/CreateRunDto.cpp.i

src/cpprest-client/model/CreateRunDto.s: src/cpprest-client/model/CreateRunDto.cpp.s

.PHONY : src/cpprest-client/model/CreateRunDto.s

# target to generate assembly for a file
src/cpprest-client/model/CreateRunDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateRunDto.cpp.s
.PHONY : src/cpprest-client/model/CreateRunDto.cpp.s

src/cpprest-client/model/CreateSubSystemPermissionDto.o: src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.o

.PHONY : src/cpprest-client/model/CreateSubSystemPermissionDto.o

# target to build an object file
src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.o
.PHONY : src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.o

src/cpprest-client/model/CreateSubSystemPermissionDto.i: src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.i

.PHONY : src/cpprest-client/model/CreateSubSystemPermissionDto.i

# target to preprocess a source file
src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.i
.PHONY : src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.i

src/cpprest-client/model/CreateSubSystemPermissionDto.s: src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.s

.PHONY : src/cpprest-client/model/CreateSubSystemPermissionDto.s

# target to generate assembly for a file
src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.s
.PHONY : src/cpprest-client/model/CreateSubSystemPermissionDto.cpp.s

src/cpprest-client/model/FlpRole.o: src/cpprest-client/model/FlpRole.cpp.o

.PHONY : src/cpprest-client/model/FlpRole.o

# target to build an object file
src/cpprest-client/model/FlpRole.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/FlpRole.cpp.o
.PHONY : src/cpprest-client/model/FlpRole.cpp.o

src/cpprest-client/model/FlpRole.i: src/cpprest-client/model/FlpRole.cpp.i

.PHONY : src/cpprest-client/model/FlpRole.i

# target to preprocess a source file
src/cpprest-client/model/FlpRole.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/FlpRole.cpp.i
.PHONY : src/cpprest-client/model/FlpRole.cpp.i

src/cpprest-client/model/FlpRole.s: src/cpprest-client/model/FlpRole.cpp.s

.PHONY : src/cpprest-client/model/FlpRole.s

# target to generate assembly for a file
src/cpprest-client/model/FlpRole.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/FlpRole.cpp.s
.PHONY : src/cpprest-client/model/FlpRole.cpp.s

src/cpprest-client/model/LinkLogToRunDto.o: src/cpprest-client/model/LinkLogToRunDto.cpp.o

.PHONY : src/cpprest-client/model/LinkLogToRunDto.o

# target to build an object file
src/cpprest-client/model/LinkLogToRunDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/LinkLogToRunDto.cpp.o
.PHONY : src/cpprest-client/model/LinkLogToRunDto.cpp.o

src/cpprest-client/model/LinkLogToRunDto.i: src/cpprest-client/model/LinkLogToRunDto.cpp.i

.PHONY : src/cpprest-client/model/LinkLogToRunDto.i

# target to preprocess a source file
src/cpprest-client/model/LinkLogToRunDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/LinkLogToRunDto.cpp.i
.PHONY : src/cpprest-client/model/LinkLogToRunDto.cpp.i

src/cpprest-client/model/LinkLogToRunDto.s: src/cpprest-client/model/LinkLogToRunDto.cpp.s

.PHONY : src/cpprest-client/model/LinkLogToRunDto.s

# target to generate assembly for a file
src/cpprest-client/model/LinkLogToRunDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/LinkLogToRunDto.cpp.s
.PHONY : src/cpprest-client/model/LinkLogToRunDto.cpp.s

src/cpprest-client/model/LinkRunToLogDto.o: src/cpprest-client/model/LinkRunToLogDto.cpp.o

.PHONY : src/cpprest-client/model/LinkRunToLogDto.o

# target to build an object file
src/cpprest-client/model/LinkRunToLogDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/LinkRunToLogDto.cpp.o
.PHONY : src/cpprest-client/model/LinkRunToLogDto.cpp.o

src/cpprest-client/model/LinkRunToLogDto.i: src/cpprest-client/model/LinkRunToLogDto.cpp.i

.PHONY : src/cpprest-client/model/LinkRunToLogDto.i

# target to preprocess a source file
src/cpprest-client/model/LinkRunToLogDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/LinkRunToLogDto.cpp.i
.PHONY : src/cpprest-client/model/LinkRunToLogDto.cpp.i

src/cpprest-client/model/LinkRunToLogDto.s: src/cpprest-client/model/LinkRunToLogDto.cpp.s

.PHONY : src/cpprest-client/model/LinkRunToLogDto.s

# target to generate assembly for a file
src/cpprest-client/model/LinkRunToLogDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/LinkRunToLogDto.cpp.s
.PHONY : src/cpprest-client/model/LinkRunToLogDto.cpp.s

src/cpprest-client/model/Log.o: src/cpprest-client/model/Log.cpp.o

.PHONY : src/cpprest-client/model/Log.o

# target to build an object file
src/cpprest-client/model/Log.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/Log.cpp.o
.PHONY : src/cpprest-client/model/Log.cpp.o

src/cpprest-client/model/Log.i: src/cpprest-client/model/Log.cpp.i

.PHONY : src/cpprest-client/model/Log.i

# target to preprocess a source file
src/cpprest-client/model/Log.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/Log.cpp.i
.PHONY : src/cpprest-client/model/Log.cpp.i

src/cpprest-client/model/Log.s: src/cpprest-client/model/Log.cpp.s

.PHONY : src/cpprest-client/model/Log.s

# target to generate assembly for a file
src/cpprest-client/model/Log.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/Log.cpp.s
.PHONY : src/cpprest-client/model/Log.cpp.s

src/cpprest-client/model/PatchFlpDto.o: src/cpprest-client/model/PatchFlpDto.cpp.o

.PHONY : src/cpprest-client/model/PatchFlpDto.o

# target to build an object file
src/cpprest-client/model/PatchFlpDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/PatchFlpDto.cpp.o
.PHONY : src/cpprest-client/model/PatchFlpDto.cpp.o

src/cpprest-client/model/PatchFlpDto.i: src/cpprest-client/model/PatchFlpDto.cpp.i

.PHONY : src/cpprest-client/model/PatchFlpDto.i

# target to preprocess a source file
src/cpprest-client/model/PatchFlpDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/PatchFlpDto.cpp.i
.PHONY : src/cpprest-client/model/PatchFlpDto.cpp.i

src/cpprest-client/model/PatchFlpDto.s: src/cpprest-client/model/PatchFlpDto.cpp.s

.PHONY : src/cpprest-client/model/PatchFlpDto.s

# target to generate assembly for a file
src/cpprest-client/model/PatchFlpDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/PatchFlpDto.cpp.s
.PHONY : src/cpprest-client/model/PatchFlpDto.cpp.s

src/cpprest-client/model/PatchRunDto.o: src/cpprest-client/model/PatchRunDto.cpp.o

.PHONY : src/cpprest-client/model/PatchRunDto.o

# target to build an object file
src/cpprest-client/model/PatchRunDto.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/PatchRunDto.cpp.o
.PHONY : src/cpprest-client/model/PatchRunDto.cpp.o

src/cpprest-client/model/PatchRunDto.i: src/cpprest-client/model/PatchRunDto.cpp.i

.PHONY : src/cpprest-client/model/PatchRunDto.i

# target to preprocess a source file
src/cpprest-client/model/PatchRunDto.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/PatchRunDto.cpp.i
.PHONY : src/cpprest-client/model/PatchRunDto.cpp.i

src/cpprest-client/model/PatchRunDto.s: src/cpprest-client/model/PatchRunDto.cpp.s

.PHONY : src/cpprest-client/model/PatchRunDto.s

# target to generate assembly for a file
src/cpprest-client/model/PatchRunDto.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/PatchRunDto.cpp.s
.PHONY : src/cpprest-client/model/PatchRunDto.cpp.s

src/cpprest-client/model/Run.o: src/cpprest-client/model/Run.cpp.o

.PHONY : src/cpprest-client/model/Run.o

# target to build an object file
src/cpprest-client/model/Run.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/Run.cpp.o
.PHONY : src/cpprest-client/model/Run.cpp.o

src/cpprest-client/model/Run.i: src/cpprest-client/model/Run.cpp.i

.PHONY : src/cpprest-client/model/Run.i

# target to preprocess a source file
src/cpprest-client/model/Run.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/Run.cpp.i
.PHONY : src/cpprest-client/model/Run.cpp.i

src/cpprest-client/model/Run.s: src/cpprest-client/model/Run.cpp.s

.PHONY : src/cpprest-client/model/Run.s

# target to generate assembly for a file
src/cpprest-client/model/Run.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/Run.cpp.s
.PHONY : src/cpprest-client/model/Run.cpp.s

src/cpprest-client/model/SubSystem.o: src/cpprest-client/model/SubSystem.cpp.o

.PHONY : src/cpprest-client/model/SubSystem.o

# target to build an object file
src/cpprest-client/model/SubSystem.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/SubSystem.cpp.o
.PHONY : src/cpprest-client/model/SubSystem.cpp.o

src/cpprest-client/model/SubSystem.i: src/cpprest-client/model/SubSystem.cpp.i

.PHONY : src/cpprest-client/model/SubSystem.i

# target to preprocess a source file
src/cpprest-client/model/SubSystem.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/SubSystem.cpp.i
.PHONY : src/cpprest-client/model/SubSystem.cpp.i

src/cpprest-client/model/SubSystem.s: src/cpprest-client/model/SubSystem.cpp.s

.PHONY : src/cpprest-client/model/SubSystem.s

# target to generate assembly for a file
src/cpprest-client/model/SubSystem.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/SubSystem.cpp.s
.PHONY : src/cpprest-client/model/SubSystem.cpp.s

src/cpprest-client/model/User.o: src/cpprest-client/model/User.cpp.o

.PHONY : src/cpprest-client/model/User.o

# target to build an object file
src/cpprest-client/model/User.cpp.o:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/User.cpp.o
.PHONY : src/cpprest-client/model/User.cpp.o

src/cpprest-client/model/User.i: src/cpprest-client/model/User.cpp.i

.PHONY : src/cpprest-client/model/User.i

# target to preprocess a source file
src/cpprest-client/model/User.cpp.i:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/User.cpp.i
.PHONY : src/cpprest-client/model/User.cpp.i

src/cpprest-client/model/User.s: src/cpprest-client/model/User.cpp.s

.PHONY : src/cpprest-client/model/User.s

# target to generate assembly for a file
src/cpprest-client/model/User.cpp.s:
	$(MAKE) -f CMakeFiles/JiskefetApiCpp.dir/build.make CMakeFiles/JiskefetApiCpp.dir/src/cpprest-client/model/User.cpp.s
.PHONY : src/cpprest-client/model/User.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... jiskefet-api-cpp-example"
	@echo "... JiskefetApiCpp"
	@echo "... src/Example.o"
	@echo "... src/Example.i"
	@echo "... src/Example.s"
	@echo "... src/JiskefetApi.o"
	@echo "... src/JiskefetApi.i"
	@echo "... src/JiskefetApi.s"
	@echo "... src/JiskefetFactory.o"
	@echo "... src/JiskefetFactory.i"
	@echo "... src/JiskefetFactory.s"
	@echo "... src/cpprest-client/ApiClient.o"
	@echo "... src/cpprest-client/ApiClient.i"
	@echo "... src/cpprest-client/ApiClient.s"
	@echo "... src/cpprest-client/ApiConfiguration.o"
	@echo "... src/cpprest-client/ApiConfiguration.i"
	@echo "... src/cpprest-client/ApiConfiguration.s"
	@echo "... src/cpprest-client/ApiException.o"
	@echo "... src/cpprest-client/ApiException.i"
	@echo "... src/cpprest-client/ApiException.s"
	@echo "... src/cpprest-client/HttpContent.o"
	@echo "... src/cpprest-client/HttpContent.i"
	@echo "... src/cpprest-client/HttpContent.s"
	@echo "... src/cpprest-client/JsonBody.o"
	@echo "... src/cpprest-client/JsonBody.i"
	@echo "... src/cpprest-client/JsonBody.s"
	@echo "... src/cpprest-client/ModelBase.o"
	@echo "... src/cpprest-client/ModelBase.i"
	@echo "... src/cpprest-client/ModelBase.s"
	@echo "... src/cpprest-client/MultipartFormData.o"
	@echo "... src/cpprest-client/MultipartFormData.i"
	@echo "... src/cpprest-client/MultipartFormData.s"
	@echo "... src/cpprest-client/Object.o"
	@echo "... src/cpprest-client/Object.i"
	@echo "... src/cpprest-client/Object.s"
	@echo "... src/cpprest-client/api/AttachmentsApi.o"
	@echo "... src/cpprest-client/api/AttachmentsApi.i"
	@echo "... src/cpprest-client/api/AttachmentsApi.s"
	@echo "... src/cpprest-client/api/AuthenticationApi.o"
	@echo "... src/cpprest-client/api/AuthenticationApi.i"
	@echo "... src/cpprest-client/api/AuthenticationApi.s"
	@echo "... src/cpprest-client/api/FlpApi.o"
	@echo "... src/cpprest-client/api/FlpApi.i"
	@echo "... src/cpprest-client/api/FlpApi.s"
	@echo "... src/cpprest-client/api/LogsApi.o"
	@echo "... src/cpprest-client/api/LogsApi.i"
	@echo "... src/cpprest-client/api/LogsApi.s"
	@echo "... src/cpprest-client/api/OverviewApi.o"
	@echo "... src/cpprest-client/api/OverviewApi.i"
	@echo "... src/cpprest-client/api/OverviewApi.s"
	@echo "... src/cpprest-client/api/RunsApi.o"
	@echo "... src/cpprest-client/api/RunsApi.i"
	@echo "... src/cpprest-client/api/RunsApi.s"
	@echo "... src/cpprest-client/api/SettingApi.o"
	@echo "... src/cpprest-client/api/SettingApi.i"
	@echo "... src/cpprest-client/api/SettingApi.s"
	@echo "... src/cpprest-client/api/SubsystemsApi.o"
	@echo "... src/cpprest-client/api/SubsystemsApi.i"
	@echo "... src/cpprest-client/api/SubsystemsApi.s"
	@echo "... src/cpprest-client/api/UsersApi.o"
	@echo "... src/cpprest-client/api/UsersApi.i"
	@echo "... src/cpprest-client/api/UsersApi.s"
	@echo "... src/cpprest-client/model/CreateAttachmentDto.o"
	@echo "... src/cpprest-client/model/CreateAttachmentDto.i"
	@echo "... src/cpprest-client/model/CreateAttachmentDto.s"
	@echo "... src/cpprest-client/model/CreateFlpDto.o"
	@echo "... src/cpprest-client/model/CreateFlpDto.i"
	@echo "... src/cpprest-client/model/CreateFlpDto.s"
	@echo "... src/cpprest-client/model/CreateLogDto.o"
	@echo "... src/cpprest-client/model/CreateLogDto.i"
	@echo "... src/cpprest-client/model/CreateLogDto.s"
	@echo "... src/cpprest-client/model/CreateRunDto.o"
	@echo "... src/cpprest-client/model/CreateRunDto.i"
	@echo "... src/cpprest-client/model/CreateRunDto.s"
	@echo "... src/cpprest-client/model/CreateSubSystemPermissionDto.o"
	@echo "... src/cpprest-client/model/CreateSubSystemPermissionDto.i"
	@echo "... src/cpprest-client/model/CreateSubSystemPermissionDto.s"
	@echo "... src/cpprest-client/model/FlpRole.o"
	@echo "... src/cpprest-client/model/FlpRole.i"
	@echo "... src/cpprest-client/model/FlpRole.s"
	@echo "... src/cpprest-client/model/LinkLogToRunDto.o"
	@echo "... src/cpprest-client/model/LinkLogToRunDto.i"
	@echo "... src/cpprest-client/model/LinkLogToRunDto.s"
	@echo "... src/cpprest-client/model/LinkRunToLogDto.o"
	@echo "... src/cpprest-client/model/LinkRunToLogDto.i"
	@echo "... src/cpprest-client/model/LinkRunToLogDto.s"
	@echo "... src/cpprest-client/model/Log.o"
	@echo "... src/cpprest-client/model/Log.i"
	@echo "... src/cpprest-client/model/Log.s"
	@echo "... src/cpprest-client/model/PatchFlpDto.o"
	@echo "... src/cpprest-client/model/PatchFlpDto.i"
	@echo "... src/cpprest-client/model/PatchFlpDto.s"
	@echo "... src/cpprest-client/model/PatchRunDto.o"
	@echo "... src/cpprest-client/model/PatchRunDto.i"
	@echo "... src/cpprest-client/model/PatchRunDto.s"
	@echo "... src/cpprest-client/model/Run.o"
	@echo "... src/cpprest-client/model/Run.i"
	@echo "... src/cpprest-client/model/Run.s"
	@echo "... src/cpprest-client/model/SubSystem.o"
	@echo "... src/cpprest-client/model/SubSystem.i"
	@echo "... src/cpprest-client/model/SubSystem.s"
	@echo "... src/cpprest-client/model/User.o"
	@echo "... src/cpprest-client/model/User.i"
	@echo "... src/cpprest-client/model/User.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

